#合格账号密码
-
  username: 135791
  password: 111111
  validata:
    type: xpath
    value: //a[text()='退出']
    expect: 退出

#已存在的账号密码
-
  username: 666666
  password: 111111
  validata:
    type: xpath
    value: //a[text()='退出']
    expect: 退出

